<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [netBankingV1]" duration-ms="42927" started-at="2020-08-06T20:02:31Z" finished-at="2020-08-06T20:03:14Z">
    <groups>
    </groups>
    <test name="BankingAppTest" duration-ms="10927" started-at="2020-08-06T20:02:31Z" finished-at="2020-08-06T20:02:42Z">
      <class name="com.netBanking.Testcase.TC_LoginTest_001">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.netBanking.Testcase.TC_LoginTest_001@ae45eb6]" name="setup" is-config="true" duration-ms="8261" started-at="2020-08-06T13:02:31Z" finished-at="2020-08-06T13:02:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.netBanking.Testcase.TC_LoginTest_001@ae45eb6]" name="loginTest" duration-ms="1309" started-at="2020-08-06T13:02:40Z" finished-at="2020-08-06T13:02:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netBanking.Testcase.TC_LoginTest_001@ae45eb6]" name="tearDown" is-config="true" duration-ms="1152" started-at="2020-08-06T13:02:41Z" finished-at="2020-08-06T13:02:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.netBanking.Testcase.TC_LoginTest_001 -->
    </test> <!-- BankingAppTest -->
    <test name="BankingAppTest(failed)" duration-ms="31319" started-at="2020-08-06T20:02:43Z" finished-at="2020-08-06T20:03:14Z">
      <class name="com.netBanking.Testcase.TC_LoginTest_001">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.netBanking.Testcase.TC_LoginTest_001@6eebc39e]" name="setup" is-config="true" duration-ms="7547" started-at="2020-08-06T13:03:05Z" finished-at="2020-08-06T13:03:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.netBanking.Testcase.TC_LoginTest_001@6eebc39e]" name="loginTest" duration-ms="1264" started-at="2020-08-06T13:03:12Z" finished-at="2020-08-06T13:03:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netBanking.Testcase.TC_LoginTest_001@6eebc39e]" name="tearDown" is-config="true" duration-ms="635" started-at="2020-08-06T13:03:13Z" finished-at="2020-08-06T13:03:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.netBanking.Testcase.TC_LoginTest_001 -->
      <class name="com.netBanking.Testcase.TC_LoginDDTest_002">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.netBanking.Testcase.TC_LoginDDTest_002@4dfa3a9d]" name="setup" is-config="true" duration-ms="7385" started-at="2020-08-06T13:02:43Z" finished-at="2020-08-06T13:02:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="LoginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.netBanking.Testcase.TC_LoginDDTest_002@4dfa3a9d]" name="LoginDDT" duration-ms="4446" started-at="2020-08-06T13:02:51Z" data-provider="LoginData" finished-at="2020-08-06T13:02:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr276598]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jahetAp]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.netBanking.Testcase.TC_LoginDDTest_002.LoginDDT(TC_LoginDDTest_002.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method status="FAIL" signature="LoginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.netBanking.Testcase.TC_LoginDDTest_002@4dfa3a9d]" name="LoginDDT" duration-ms="4425" started-at="2020-08-06T13:02:55Z" data-provider="LoginData" finished-at="2020-08-06T13:03:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr123456]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ertyhoi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.netBanking.Testcase.TC_LoginDDTest_002.LoginDDT(TC_LoginDDTest_002.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method status="FAIL" signature="LoginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.netBanking.Testcase.TC_LoginDDTest_002@4dfa3a9d]" name="LoginDDT" duration-ms="4045" started-at="2020-08-06T13:03:00Z" data-provider="LoginData" finished-at="2020-08-06T13:03:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr098765]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[gurmani]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.netBanking.Testcase.TC_LoginDDTest_002.LoginDDT(TC_LoginDDTest_002.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDT -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.netBanking.Testcase.TC_LoginDDTest_002@4dfa3a9d]" name="tearDown" is-config="true" duration-ms="683" started-at="2020-08-06T13:03:04Z" finished-at="2020-08-06T13:03:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.netBanking.Testcase.TC_LoginDDTest_002 -->
    </test> <!-- BankingAppTest(failed) -->
  </suite> <!-- Failed suite [netBankingV1] -->
</testng-results>
